apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  backend-store-uri: postgresql://mlflow:mlflowpassword@postgres:5432/mlflowdb
  artifact-root: /mlflow/artifacts